<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function photo_gallery_theme($existing, $type, $theme, $path) {
  return [
    'views_view__photo_gallery__block' => [
      'template' => 'views-view--photo-gallery--block',
      'base hook' => 'views',
    ],
    'views_view__photo_gallery__gallery_single_slideshow' => [
      'template' => 'views-view--photo-gallery--gallery-single-slideshow',
      'base hook' => 'views',
    ],
    'views_view__photo_gallery__gallery_single' => [
      'template' => 'views-view--photo-gallery--gallery-slideshow-banner',
      'base hook' => 'views',
    ],
    'views_view__photo_gallery__page' => [
      'template' => 'views-view--photo-gallery--page',
      'base hook' => 'views',
    ],
    'views_view__photo_gallery__gallery_slideshow_banner' => [
      'template' => 'views-view--photo-gallery--gallery-slideshow-banner',
      'base hook' => 'views',
    ],
  ];
}

/**
* Implements hook_views_pre_render().
*/
function photo_gallery_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'photo_gallery')) {
    $view->element['#attached']['library'][] = 'photo_gallery/photo-gallery-views';
  }
}

/**
 * Implements hook_preprocess_node().
*/

function photo_gallery_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->getType() == 'gallery_photo') {
    $variables['#attached']['library'][] = 'photo_gallery/photo-gallery-node';
  }
}
